### ISSUE TITLE
wishlist: Ability to resume from a given image number

### ISSUE THREAD

**Issue by zorael** [Wipie/LightShotGalleryDownloader-CLI#2]
Since prnt.sc has become increasingly unreliable, I wanted to pull all my pictures off it. When using this program normally I ended up being very aggressively rate-limited, so I had to uncomment the `wait` in function `extractScreenshots` and give it a number of `60000`, then let it work for a few days.

Even so, at one point (after 802 images) a connection still failed with `ECONNRESET` and the program exited. I didn't want to start all over from the beignning, so I merely set the `for` loop (also in function `extractScreenshots`) to start at that number, and ran it again.

```diff
diff --git a/index.js b/index.js
index e90daaa..c8735b3 100644
--- a/index.js
+++ b/index.js
@@ -34,8 +34,8 @@ async function extractScreenshots(file) {
   console.log("==============By Wipie=============================");
   console.log("===================================================");
   pBar.start(file.result.total, 0);
-  for(let i = 0; i < file.result.total; i++) {
-      //wait(1000); // Pausing thread to avoid Prntscr's timeout
+  for(let i = 802; i < file.result.total; i++) {
+      wait(60000); // Pausing thread to avoid Prntscr's timeout
       pBar.increment();
       pBar.updateETA()
       pBar.update(i, {
```

It would be convenient if a starting point could somehow be set without modifying the source.

**Comment by Wipie** [comment]
Hey mate, thanks for your feedback, I gotta say I haven't used it nor maintain it since I released it so I will check how come their cloudflare is kicking this early now. Back then I could do a 5-10k runs without crash with only a 1 secondes delay. Anyways, I'm currently quite busy IRL. But as soon as I get more time I will implement your idea

**Comment by Wipie** [comment]
Sorry it took a bit longer then I actually planned it to be because I was really busy IRL. Here it is now you can simply do a node . <number> and it will start e.g: node . 100 will start at index 100
